import Head from 'next/head'
import Image from 'next/image'
import { Nunito } from 'next/font/google'


const nunito = Nunito({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={nunito.className}>
     <h1 className=''>hello</h1>
      </main>
    </>
  )
}
